//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WirenetApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ElectricianServiceBookingEntities : DbContext
    {
        public ElectricianServiceBookingEntities()
            : base("name=ElectricianServiceBookingEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserService> UserServices { get; set; }
        public virtual DbSet<adminE> adminEs { get; set; }
        public virtual DbSet<LoginI> LoginIs { get; set; }
    }
}