//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WirenetApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class ServiceProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceProvider()
        {
            this.UserServices = new HashSet<UserService>();
        }
    
        public int Sid { get; set; }
        [Required]
        public string FullName { get; set; }
        [Required]
        [RegularExpression("^[6-9]{1}[0-9]{9}$", ErrorMessage = "Invalid mobile number")]
        public long Phoneno { get; set; }
        [Display(Name = "Email address")]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Emailid { get; set; }
        [Required]
        public string Specialization { get; set; }
        [Required]
        [Remote("IsElectricianIDNameExist", "UniqueEID", AdditionalFields = "id",
                ErrorMessage = "electrician licenseID already exists")]
        public string ElectricianID { get; set; }
        [Required]
        public string experience { get; set; }
        [Required]
        public int rangeperhour { get; set; }
        [Required]
        [RegularExpression("^[SP]{2}[0-9]{5}$", ErrorMessage = "The username should be in the fromat like 'SP' followed by 5 numbers")]
        [Remote("IsElectricianUserNameExist", "Unique", AdditionalFields = "Id",
                ErrorMessage = "Username name already exists")]
        public string username { get; set; }
        [Required]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserService> UserServices { get; set; }
    }
}
