//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WirenetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceProvider()
        {
            this.UserServices = new HashSet<UserService>();
        }
    
        public int Sid { get; set; }
        public string FullName { get; set; }
        public long Phoneno { get; set; }
        public string Emailid { get; set; }
        public string Specialization { get; set; }
        public string ElectricianID { get; set; }
        public string experience { get; set; }
        public int rangeperhour { get; set; }
        public string username { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserService> UserServices { get; set; }
    }
}
