//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WirenetApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserService
    {
        public Nullable<int> Uid { get; set; }
        public Nullable<int> sid { get; set; }
        public string timing { get; set; }
        public int usid { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{YYYY/MM/DD}")]
        public Nullable<System.DateTime> datevalue { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual User User { get; set; }
    }
}
